### ISSUE TITLE
Hide additional scrollbar

### ISSUE THREAD

**Issue by MikPisula** [Kacper1263/dbfm-firefox#2]
### Issue
An additional light-themed scrollbar is visible in Messenger. This scrollbar seems to not contribute any functionality and is simply an eyesore. 
![image](https://user-images.githubusercontent.com/47534140/150785247-45cf52ed-4a4a-40be-bf7c-993005e2138c.png)

#### Browser
| Name | Firefox |
| --- | --- | 
Version | 96.0.2
Build ID | 20220119190439

### Suggested fix
Appending the following code to `style.css` hides the scrollbar.
```css
._9dls {
    overflow-y: hidden !important;
}
```

**Comment by Kacper1263** [comment]
Thanks for all the information and suggested fix. The current version of the plugin with your code is now available on AMO (addons.mozilla.org). Thanks for contributing!
